alias l='ls -G'
alias la='ls -aG'
alias ll='ls -lG'
alias lla='ls -laG'

alias dc='docker-compose'

bind '"\C-f": forward-word'
bind '"\C-b": backward-word'

echo 'C-p history'
echo 'C-r C-s Search'
echo 'C-f C-b forward-word'
echo 'C-u clear line'
echo 'C-w back word'
echo 'C-a C-b beginning line'

stty stop undef
